<h2>Sign up using this form</h2>
<div style="padding: 10px">
<?php echo $this->tag->form(["signup/process", "class" => "form-group"]); ?>
    <label for="name" class="col-sm-3 col-form-label">Name</label>
    <div class="col-sm-9">
        <?php echo $this->tag->textField([ "name", "class" => "form-control"]); ?>
    </div>
    <br/><br/>
    <label for="email" class="col-sm-3 col-form-label">E-Mail</label>
    <div class="col-sm-9">
        <?php echo $this->tag->textField(["email", "class" => "form-control"]); ?>
    </div>
    <br/><br/>
    <label for="password" class="col-sm-3 col-form-label">Password</label>
    <div class="col-sm-9">
        <?php echo $this->tag->passwordField(["password", "class" => "form-control"]); ?>
    </div>
    <br/><br/>
    <label for="password" class="col-sm-3 col-form-label">Password Confirmation</label>
    <div class="col-sm-9">
        <?php echo $this->tag->passwordField(["password_confirmation", "class" => "form-control"]); ?>
    </div>
    <input type="hidden" name="<?php echo $this->security->getTokenKey() ?>" value="<?php echo $this->security->getToken() ?>" />

    <?php echo $this->tag->submitButton([
        "Register",
        "style" => "margin-top: 20px;font-size:large"
    ]); ?>

</form>
</div>