<h2>Sign up using this form</h2>

<?php echo $this->tag->form("signup/register"); ?>

<p>
    <label for="name">Name</label>
    <?php echo $this->tag->textField("name"); ?>
</p>

<p>
    <label for="email">E-Mail</label>
    <?php echo $this->tag->textField("email"); ?>
</p>

<p>
    <label for="password">Password</label>
    <?php echo $this->tag->textField("password"); ?>
</p>

<p>
    <?php echo $this->tag->submitButton("Register"); ?>
</p>

</form>

<?php if(property_exists($single , 'id')): ?>
    <?=$single->id?>
    <?=$single->email?>
<?php endif; ?>

<hr/>

<h1>Users</h1>
<?php foreach ($all as $user): ?>
    <?=$user->id?>
    <?=$user->name?>
    <?=$user->email?>
    <?= count($user->orders)>0 ? $user->orders[0]->id : 'nop' ?>
    <br/>
<?php endforeach; ?>
