<h2>Create order items using this form</h2>
<div style="padding: 10px">
<?php echo $this->tag->form(['orders/'.$id.'/create', "class" => "form-group"]); ?>

    <label for="product_name" class="col-sm-3 col-form-label">Product name</label>
    <div class="col-sm-9">
        <?php echo $this->tag->textField(["product", "class" => "form-control"]); ?>
    </div>
    <br/><br/>
    <label for="qty" class="col-sm-3 col-form-label">Quantity</label>
    <div class="col-sm-9">
        <?php echo $this->tag->textField(["qty", "class" => "form-control"]); ?>
    </div>
    <br/><br/>
    <label for="price" class="col-sm-3 col-form-label">Price</label>
    <div class="col-sm-9">
        <?php echo $this->tag->textField(["price", "class" => "form-control"]); ?>
    </div>
    <input type="hidden" name="<?php echo $this->security->getTokenKey() ?>" value="<?php echo $this->security->getToken() ?>" />

    <?php echo $this->tag->submitButton([
        "Submit",
        "style" => "margin-top: 20px;font-size:large"
    ]); ?>

</form>
</div>