<h2>Login using this form</h2>
<div style="padding: 10px">
<?php echo $this->tag->form(["login/process", "class" => "form-group"]); ?>

    <label for="email" class="col-sm-3 col-form-label">E-Mail</label>
    <div class="col-sm-9">
    <?php echo $this->tag->textField(["email", "class" => "form-control"]); ?>
    </div>
    <br/><br/>
    <label for="password" class="col-sm-3 col-form-label">Password</label>
    <div class="col-sm-9">
    <?php echo $this->tag->passwordField(["password", "class" => "form-control"]); ?>
    </div>
    <input type="hidden" name="<?php echo $this->security->getTokenKey() ?>" value="<?php echo $this->security->getToken() ?>" />

    <?php echo $this->tag->submitButton([
        "Login",
        "style" => "margin-top: 20px;font-size:large"
    ]); ?>

</form>
</div>