<!doctype html>
<html>
<head>
    <?php echo $this->tag->getTitle() ?>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <?php $this->assets->outputCss('style'); ?>
    <?php $this->assets->outputJs('js'); ?>
</head>

<body>

<div class="navbar navbar-default">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">Phalcon</a>
        </div>

        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li class="d"><a href="/">Home</a></li>
                <?php
                if(isUserLoggedIn())
                    echo '<li class="d"><a href="/orders/all">Orders</a></li>';
                else
                    echo '<li class="d"><a href="/signup">Register</a></li>';
                ?>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <?php
                if($this->session->get('user')) {
                ?>
                <li class="dropdown">
                    <a class="dropdown-toggle" href="#"  data-toggle="dropdown">
                        <?php echo $this->session->get('user')->name ?>
                    </a>
                    <ul class="dropdown-menu">
                        <li><a href="/logout">logout</a></li>
                    </ul>
                </li>
                <?php
                }
                else
                    echo '<li><a href="/login">Signin</a></li>';
                ?>
            </ul>
        </div>

        <p><?php $this->flashSession->output(); ?></p>
        <div class="jumbotron">
            <?=$this->getContent();?>
        </div>
    </div>
</div>

</body>
<script type="text/javascript">
    setDefaultActive()
</script>
</html>
